Controllers/AmiController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using TaskBuddy.Data;
using TaskBuddy.Models;


namespace TaskBuddy.Controllers
{
    public class AmiController : Controller
    {
        private readonly UserManager<Utilisateur> userManager;

        private readonly ApplicationDbContext _dbcontext;


        public AmiController(UserManager<Utilisateur> userManager,
           ApplicationDbContext dbcontext
           )
        {
            this.userManager = userManager;

            _dbcontext = dbcontext;



        }
        [HttpGet]

        public IActionResult search(string nameSearch)
        {
            return View(userManager.Users.Where(x => x.UserName.Contains(nameSearch) || nameSearch == null).ToList());
        }

        [HttpGet]
        public IActionResult listeAmis()
        {
            // Obtenez l'ID de l'utilisateur connecté (assurez-vous que votre système d'authentification est configuré)
            var utilisateurId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Récupérez la liste des amis de l'utilisateur connecté depuis la base de données
            var listeAmis = _dbcontext.Amis
                .Include(a => a.AmiUtilisateur) // Inclure l'utilisateur ami
                .Where(a => a.UtilisateurId == utilisateurId)
                .ToList();

            // Passez la liste des amis à la vue
            return View(listeAmis);
        }


    }
}

Controllers/InvitationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskBuddy.Data;
using TaskBuddy.Models;


namespace TaskBuddy.Controllers
{
    public class InvitationController : Controller
    {
        private readonly UserManager<Utilisateur> userManager;

        private readonly ApplicationDbContext _dbcontext;


        public InvitationController(UserManager<Utilisateur> userManager,
          ApplicationDbContext dbcontext
           )
        {
            this.userManager = userManager;

            _dbcontext = dbcontext;



        }

        [HttpGet]

        public IActionResult search(string nameSearch)
        {
            return View(_dbcontext.Invitations.Where(x => x.DestinataireId.Contains(nameSearch) || nameSearch == null).ToList());
        }


        [HttpPost]
        public IActionResult invitations(string Id)
        {
            var expediteurId = userManager.GetUserId(User); // Obtenez l'ID de l'utilisateur connecté comme expéditeur

            var invitation = new Invitation
            {
                ExpediteurId = expediteurId,
                DestinataireId = Id,
                IsAccepted = false
                // Vous pouvez ajouter d'autres propriétés d'invitation ici
            };

            _dbcontext.Invitations.Add(invitation);
            _dbcontext.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult AccepterInvitation(int invitationId)
        {
            var invitation = _dbcontext.Invitations.Find(invitationId);

            if (invitation != null && !invitation.IsAccepted && !invitation.IsDeclined)
            {
                invitation.IsAccepted = true;

                var destinataireId = invitation.DestinataireId;
                var expediteurId = invitation.ExpediteurId;

                // Ajoutez l'ami dans la table Ami
                _dbcontext.Amis.Add(new Ami { UtilisateurId = destinataireId, AmiId = expediteurId });

                _dbcontext.SaveChanges();
            }

            return Ok(); // Ou une autre réponse appropriée
        }

        private void AjouterAmi(string utilisateurId, string amiId)
        {
            // Logique pour ajouter l'ami (vous devrez ajuster cela en fonction de votre modèle)
            // Exemple : _dbcontext.Amis.Add(new Ami { UtilisateurId = utilisateurId, AmiId = amiId });
        }

        [HttpGet]
        public IActionResult InvitationEnvoye()
        {
            var userId = userManager.GetUserId(User);

            var invitationsEnvoyees = _dbcontext.Invitations
                .Include(i => i.Destinataire)  // Inclure l'utilisateur destinataire
                .Where(i => i.ExpediteurId == userId)
                .ToList();

            return View(invitationsEnvoyees);
        }

        [HttpGet]
        public IActionResult AfficherInvitations()
        {
            var userId = userManager.GetUserId(User);

            var invitations = _dbcontext.Invitations
                .Include(i => i.Expediteur)  // Inclure l'utilisateur destinataire
                .Where(i => i.DestinataireId == userId && !i.IsAccepted)
                .ToList();

            return View(invitations);
        }

    }
}

Controllers/TacheController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.Xml;
using TaskBuddy.Data;
using TaskBuddy.Models;

namespace TaskBuddy.Controllers
{
    [Authorize]
    public class TacheController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<Utilisateur> _userManager;

        public TacheController(ApplicationDbContext dbContext, UserManager<Utilisateur> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }
        [HttpGet]

        public IActionResult search(string nameSearch)
        {
            return View(_dbContext.Tasks.Where(x => x.Nom.Contains(nameSearch) || nameSearch == null).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> ListeTaches()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var userTasks = _dbContext.Tasks.Where(task => task.UserId == currentUser.Id).ToList();

            return View(userTasks);
        }

        [HttpGet]
        public IActionResult CreateTache() {
            return View();
                
         }
        [HttpPost]
        public async Task<IActionResult> CreateTache(Tache tache)
        {
            var userId = _userManager.GetUserId(User);
            if (userId != null)
            {
                tache.UserId = userId;
                tache.Etat = "in progress";
                if (tache.Priority == "High") tache.Reward = 3;
               else if (tache.Priority == "Medium") tache.Reward = 2;
               else if (tache.Priority == "Low") tache.Reward = 1;
                tache.DateD = DateTime.Now;
                _dbContext.Tasks.Add(tache);
                _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(ListeTaches)) ;
        }
        [HttpGet]
        public IActionResult Details(int id) {
        
        var tache=_dbContext.Tasks.SingleOrDefault (t => t.IdTask == id);
            return View(tache);
        
        }
        
        [HttpGet]
        [HttpPost]
        public IActionResult DeleteTache(int id)
        {   
            var tache = _dbContext.Tasks.SingleOrDefault(t => t.IdTask == id);
            if (tache != null)
            {
                _dbContext.Tasks.Remove(tache);
                _dbContext.SaveChanges();

            }
            return RedirectToAction(nameof(ListeTaches));
        }
       
        [HttpGet]
        public IActionResult EditTache(int id)
        {
            var tache= _dbContext.Tasks.Find(id);
            return View(tache);
        }
        [HttpPost]  
        public IActionResult EditTache(Tache newTache)
        {
            var oldTache= _dbContext.Tasks.Find(newTache.IdTask);
            if(oldTache != null) { 
            
            oldTache.Nom=newTache.Nom;
            oldTache.DateD = newTache.DateD;
            oldTache.DateF=newTache.DateF;
            oldTache.Note = newTache.Note;
             _dbContext.SaveChanges();
            }
            return RedirectToAction(nameof(ListeTaches));
        }

        [HttpPost]
        [Route("Tache/UpdateStatus/{id}")]
        public async Task<IActionResult> UpdateTaskStatus(int id)
        { var user = await _userManager.GetUserAsync(User);
            var task = _dbContext.Tasks.Find(id);

            if (task != null && user != null)
            {
                task.Etat = task.Etat == "in progress" ? "done" : "in progress";
                _dbContext.Update(task);
                if (task.Etat=="done") user.MyScore += task.Reward;
                else if (task.Etat=="in progress" && user.MyScore!=0) user.MyScore -= task.Reward;
                await _userManager.UpdateAsync(user);
                _dbContext.SaveChanges();
                return Ok();
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> PartagerTache()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            // Retrieve tasks associated with the current user
            var userTasks = _dbContext.Tasks.Where(task => task.UserId == currentUser.Id).ToList();

            return View(userTasks);
        }

        [HttpPost]


        public IActionResult PartagerTache(int tacheId)
        {
            var userId = _userManager.GetUserId(User);

            // Récupérez la tâche que vous partagez
            var tache = _dbContext.Tasks.Find(tacheId);

            // Récupérez la liste des amis de l'utilisateur
            var amis = _dbContext.Amis.Where(a => a.UtilisateurId == userId).ToList();

            // Partagez la tâche avec chaque ami
            foreach (var ami in amis)
            {
                var tachePartagee = new TachePartagee
                {
                    TacheId = tacheId,
                    Tache = tache,
                    ExpediteurId = userId,
                    Expediteur = tache.Utilisateur, // Utilisateur qui partage la tâche
                    DestinataireId = ami.AmiId,
                    Destinataire = ami.AmiUtilisateur // Utilisateur destinataire
                };

                _dbContext.TachesPartagees.Add(tachePartagee);
            }

            _dbContext.SaveChanges();

            return Json(new { success = true });
        }


    }
}

Controllers/UtilisateurController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TaskBuddy.Data;
using TaskBuddy.Models;
using System.Net;
using Test.Areas.Identity.Pages.Account.Manage;
using System.ComponentModel.DataAnnotations;
using TaskBuddy.Areas.Identity.Pages.Account;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.WebUtilities;
using System.Text.Encodings.Web;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace TaskBuddy.Controllers
{
    [Authorize]
    public class UtilisateurController : Controller
    {

        private readonly UserManager<Utilisateur> userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly SignInManager<Utilisateur> _signInManager;
        private readonly IUserStore<Utilisateur> _userStore;
        private readonly IUserEmailStore<Utilisateur> _emailStore;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;

        


        public UtilisateurController(UserManager<Utilisateur> userManager,
            IUserStore<Utilisateur> userStore,
            SignInManager<Utilisateur> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            IWebHostEnvironment webHostEnvironment)
        {
            this.userManager = userManager;
            _userStore = userStore;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _webHostEnvironment = webHostEnvironment;
        }


        //--------------------------------------


        [HttpGet]
        public IActionResult ListeUtilisateur()
        {
            var users = userManager.Users.ToList();
            return View(users);
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListeUtilisateur");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListeUtilisateur");
            }
        }

        [HttpGet]

        public IActionResult search(string nameSearch)
        {
            return View(userManager.Users.Where(x => x.UserName.Contains(nameSearch) || nameSearch == null).ToList());
        }
        [HttpGet]
        public async Task<IActionResult> UserDetails(string id)
        {  var user= await userManager.FindByIdAsync(id);

            return View(user);
        }       

        [HttpGet]
        public async Task<IActionResult> EditUtilisateur(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            return View(user);
        }


        [HttpPost]
        public async Task<IActionResult> EditUtilisateur(Utilisateur newUser)
        {
            var oldUser = await userManager.FindByIdAsync(newUser.Id);
            if (oldUser != null)
            {

                oldUser.Role = newUser.Role;

                var result = await userManager.UpdateAsync(oldUser);

                /*
                if (result.Succeeded)
                {
                    await _signInManager.RefreshSignInAsync(oldUser);
                    return RedirectToAction(nameof(ListeUtilisateur));
                }
                else
                {
                    await _signInManager.RefreshSignInAsync(oldUser);
                    return RedirectToAction(nameof(ListeUtilisateur));

                }
                */
            }
            return RedirectToAction(nameof(ListeUtilisateur));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Utilisateur> SignInManager
@inject UserManager<Utilisateur> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskBuddy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css"  />
    <link rel="stylesheet" href="~/TaskBuddy.styles.css" asp-append-version="true" />
</head>


<body>
    @if (!SignInManager.IsSignedIn(User))
    {
        <header>
            <div style="width: 100%; background:white;position:fixed;z-index:100;">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
                    <div class="container-fluid">
                        
                        <div class="logo" style="margin-left: 208px;"><span>TaskBuddy</span></div>
                        <ul style="list-style:none;text-align:center;width:100%;padding:0;margin:0;">
                            <li class="title layout_focus" onclick="scrollToHomeSection()">Home</li>
                            <li class="title" onclick="scrollToFeaturesSection()">Features</li>
                            <li class="title" onclick="scrollToPartnersSection()">Our Partners</li>
                            
                            <li class="title" onclick="scrollToAboutSection()">About Us</li>
                        </ul>
                        <div class="login" style="margin-right: 200px;"><partial name="_LoginPartial" /></div>
                    </div>
                </nav>
            </div>
        </header>
    }
    else
    {
        <!--Left SideBar-->
        <div  class="leftsidenav">
            <a asp-area="" asp-controller="Home" asp-action="Dashboard"><i class="fa-brands fa-flipboard sideBar_logo"></i></a>
            <!-- search --><a class="nav-link text-dark" asp-area="" asp-controller="Utilisateur" asp-action="search"><i class="fa-solid fa-magnifying-glass"></i></a>
            <a class="nav-link text-dark" asp-area="" asp-controller="Ami" asp-action="listeAmis"><i class="fa-solid fa-user-tie"></i></a>
            <a class="nav-link text-dark" asp-area="" asp-controller="Invitation" asp-action="InvitationEnvoye"><i class="fa-solid fa-user-clock"></i></a><!--Invi env-->
            <a class="nav-link text-dark" asp-area="" asp-controller="Invitation" asp-action="AfficherInvitations"><i class="fa-solid fa-user-check"></i></a><!-- Invi recu -->
            <a class="nav-link text-dark" asp-area="" asp-controller="Tache" asp-action="PartagerTache"><i class="fa-solid fa-share"></i></a>
            <a class="nav-link text-dark" asp-area="" asp-controller="TachePartagee" asp-action="listeAmis"><i class="fa-solid fa-users"></i></a><!-- Invi recu -->
            @if (UserManager.GetUserAsync(User).Result.Role == "admin")
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="Utilisateur" asp-action="ListeUtilisateur"><i class="fa-solid fa-users-gear"></i></a>
            }
            <a title="Manage" asp-area="Identity" asp-page="/Account/Manage/ProfileChange"><i class="fa-solid fa-gear sideBar_settings"></i></a>
        </div>
        <!--Right SideBar-->
        <div class="rightsidenav">
            <partial name="_LoginPartial" />


            <div class="calendar">
                <div class="header">
                    <button class="prev" onclick="prevMonth()">&#10094;</button>
                    <h2 id="month-year"></h2>
                    <button class="next" onclick="nextMonth()">&#10095;</button>
                </div>
                <div class="weekdays">
                    <div>Sun</div>
                    <div>Mon</div>
                    <div>Tue</div>
                    <div>Wed</div>
                    <div>Thu</div>
                    <div>Fri</div>
                    <div>Sat</div>
                </div>
                <div class="days" id="calendar-days"></div>
            </div>
            <div class="task_history">
                <div class="header">
                    Mastering the Art of Task Creation!
                </div>
                <div class="history">

                    <ul style="line-height: 3.2;">
                        <li>
                            <strong>Define with Precision</strong>
                        </li>
                        <li>
                            <strong>Break It Down Strategically</strong>
                        </li>
                        <li>
                            <strong>Set Timeframes for Triumph</strong>
                        <li>
                            <strong>Equip Yourself</strong>
                        </li>
                        <li>
                            <strong>Harness TaskBuddy's Potential</strong> 
                        </li>
                    </ul>
                   
                    

                </div>
            </div>
        </div>
        
    }
<main role="main">
    @RenderBody()
</main>
        

    @if (!SignInManager.IsSignedIn(User))
    {
        <footer style="background:#7D4FFE;overflow:hidden;">
            <div class="footer_img">
                <img src="~/assests/Footer.png" />
            </div>
            <div class="container">
                <div class="footer_infos row">
                    <div class="footer_logo col-6">TaskBuddy</div>
                    <div class="footer_liste col-6">
                        <ul style="list-style:none">
                            <li>Home</li>
                            <li>About Us</li>
                            <li>Contact Us</li>
                        </ul>
                    </div>
                </div>
                <div class="footer_social">
                    <i class="fa-brands fa-facebook" style="cursor:pointer;"></i>
                    <i class="fa-brands fa-instagram" style="cursor:pointer;"></i>
                    <i class="fa-brands fa-linkedin" style="cursor:pointer;"></i>
                </div>
                <div class="footer_copy">
                    &copy; Copyright.All rights reserved - Made With Love &hearts;
                </div>
        </div>
    </footer>
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>